//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonkoraEdge.Core.Auth.Domain.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonkoraEdge.Core.Auth.Domain.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username is already taken. Please choose another one..
        /// </summary>
        internal static string account_exists_choose_another_one {
            get {
                return ResourceManager.GetString("account_exists_choose_another_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This display name is already taken. Please choose another one..
        /// </summary>
        internal static string display_name_exists_choose_another_one {
            get {
                return ResourceManager.GetString("display_name_exists_choose_another_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Staff exists. Please go use.
        /// </summary>
        internal static string failed_account_staff_duplicate {
            get {
                return ResourceManager.GetString("failed_account_staff_duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement Accept exists. Please go use.
        /// </summary>
        internal static string failed_agreement_accept_duplicate {
            get {
                return ResourceManager.GetString("failed_agreement_accept_duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement exists. Please go use.
        /// </summary>
        internal static string failed_agreement_duplicate {
            get {
                return ResourceManager.GetString("failed_agreement_duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module exists. Please go use.
        /// </summary>
        internal static string failed_module_duplicate {
            get {
                return ResourceManager.GetString("failed_module_duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization exists. Please go use.
        /// </summary>
        internal static string failed_organization_duplicate {
            get {
                return ResourceManager.GetString("failed_organization_duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission exists. Please go use.
        /// </summary>
        internal static string failed_permission_duplicate {
            get {
                return ResourceManager.GetString("failed_permission_duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform exists. Please go use.
        /// </summary>
        internal static string failed_platform_duplicate {
            get {
                return ResourceManager.GetString("failed_platform_duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider exists. Please go use.
        /// </summary>
        internal static string failed_provider_duplicate {
            get {
                return ResourceManager.GetString("failed_provider_duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role exists. Please go use.
        /// </summary>
        internal static string failed_role_duplicate {
            get {
                return ResourceManager.GetString("failed_role_duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username exists. Please go to sign-in..
        /// </summary>
        internal static string failed_username_duplicate {
            get {
                return ResourceManager.GetString("failed_username_duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social account is incorrect, Please try again..
        /// </summary>
        internal static string invalid_social {
            get {
                return ResourceManager.GetString("invalid_social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email or password is incorrect, Please try again..
        /// </summary>
        internal static string invalid_username_or_password {
            get {
                return ResourceManager.GetString("invalid_username_or_password", resourceCulture);
            }
        }
    }
}
